/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package swerve;

import org.junit.Ignore;
import org.junit.Test;

@Ignore
public class LibraryTest {
    
    @Test
    public void testSomeLibraryMethod() {}
}